name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check versions
        id: check
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          PKG_VERSION="v$(node -p "require('./package.json').version")"
          echo "tag=${TAG}" >> "$GITHUB_OUTPUT"
          MATCH="$([ "${TAG}" = "${PKG_VERSION}" ] && echo true || echo false)"
          echo "tag=$TAG, version=$PKG_VERSION => match = $MATCH"
          echo "match=$MATCH" >> "$GITHUB_OUTPUT"

      - name: Bump version and re-tag
        id: retag
        if: steps.check.outputs.match == 'false'
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          npm version "${{ steps.check.outputs.tag }}" --allow-same-version
          git push origin HEAD:${{ github.event.repository.default_branch }}
          git push origin "${{ steps.check.outputs.tag }}" --force
          echo "match=true" >> "$GITHUB_OUTPUT"

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        if: steps.check.outputs.match == 'true' || steps.retag.outputs.match == 'true'
        with:
          node-version: 22
          cache: pnpm

      - name: Install and publish
        if: steps.check.outputs.match == 'true' || steps.retag.outputs.match == 'true'
        run: |
          pnpm install --frozen-lockfile
          pnpm build
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          pnpm publish --access public --no-git-checks

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

